### PR TITLE
Grocy docker patch

### PR DESCRIPTION
**Pull request by talmai**
Hi Berrnd. Awesome job with Grocy. This PR allows anyone to run a dockerized version of Grocy.

### CODE REVIEW

**Comment by berrnd** [comment]
Cool! :)

Although I don't use Docker myself, this was requested a few times - so I'd be happy to add that just as it is...

Thanks!

**Comment by cmantsch** [comment]
Could you provide Details how to run it @talmai? I cloned the Repository and ran _docker-compose up_ 
I only get a white screen when accessing with a Browser.

**Comment by talmai** [comment]
I actually pulled and tried, and hit the following error:

```
Warning: Use of undefined constant GROCY_USER_ID - assumed 'GROCY_USER_ID' (this will throw an Error in a future version of PHP) in /www/controllers/BaseController.php on line 47
```

a quick fix was to add a check:

```
			if (defined('GROCY_USER_ID')) {
				$container->view->set('userSettings', $usersService->GetUserSettings(GROCY_USER_ID));
			}
```

You prefer I open a new PR with the fix, or want to just update it yourself?

**Comment by talmai** [comment]
just opened a PR

**Comment by cmantsch** [comment]
works like a charm now, thanks!

**Pull request merged**
